user_name = ("xpath", '//*[@id="user-name"]')
password = ("xpath", '//*[@id="password"]')
login = ("xpath", '//*[@id="login-button"]')
add_to_card = ("xpath", '//div[contains(text(), "$")]/following-sibling::button')
remove = ("xpath", '//button[contains(text(), "Remove")]')
basket = ("xpath", '//a[@class="shopping_cart_link"]')
quantity_of_goods = ("xpath", '//*[@id="shopping_cart_container"]/a/span')
product_name = ("xpath", '//div[contains(text(), "Sauce Labs Bolt T-Shirt")]')
product_picture = ("xpath", '//img[@alt="Sauce Labs Bolt T-Shirt"]')
checkout = ("xpath", '//button[contains(text(), "Checkout")]')
menu = ("xpath", '//button[@id="react-burger-menu-btn"]')
first_name = ("xpath", '//*[@id="first-name"]')
last_name = ("xpath", '//*[@id="last-name"]')
button_continue = ("xpath", '//*[@id="continue"]')
button_finish = ("xpath", '//*[@id="finish"]')
title = ("xpath", '//span[contains(text(), "Products")]')
all_product = ("xpath", '//*[@class="inventory_item_desc"]')
button_filter = ("xpath", '// select[ @class ="product_sort_container"]')
names_product = ("xpath", '// div[ @class ="inventory_item_name "]')
add_to_cart_page_product = ("xpath", '//button[contains(text(), "Add to cart")]')
price_product = ("xpath", '//div[contains(text(), "$")]')
