user_name = ("xpath", '//*[@id="user-name"]')
password = ("xpath", '//*[@id="password"]')
login = ("xpath", '//*[@id="login-button"]')
add_to_card = ("xpath", '//div[contains(text(), "$")]/following-sibling::button')
remove = ("xpath", '//button[contains(text(), "Remove")]')
basket = ("xpath", '//a[@class="shopping_cart_link"]')
quantity_of_goods = ("xpath", '//*[@id="shopping_cart_container"]/a/span')
product_name = ("xpath", '//div[contains(text(), "Backpack")]')
product_picture = ("xpath", '//img[@alt="Sauce Labs Bolt T-Shirt"]')
checkout = ("xpath", '//button[contains(text(), "Checkout")]')
menu = ("xpath", '//button[@id="react-burger-menu-btn"]')
